### ISSUE TITLE
Breaking change after upgrading Swashbuckle.AspNetCore to 10.x due to Microsoft.OpenApi 2.x

### ISSUE THREAD

**Issue by hansos** [hansos/DR_Admin#36]
# Breaking change after upgrading Swashbuckle.AspNetCore to 10.x due to Microsoft.OpenApi 2.x

## Description
After upgrading `Swashbuckle.AspNetCore` from version **7.2.0** to **10.1.0**, which brings in `Microsoft.OpenApi` **2.3.0**, existing code that relied on the `Microsoft.OpenApi` 1.x API is failing. The `Microsoft.OpenApi` 2.x introduces significant API changes that are not backward compatible with version 1.x.

## Steps to Reproduce
1. Upgrade `Swashbuckle.AspNetCore` from `7.2.0` to `10.1.0`.
2. Attempt to build or run code that references `Microsoft.OpenApi` APIs from version 1.x.
3. Observe compilation errors or runtime issues due to API incompatibility.

## Expected Behavior
Upgrading `Swashbuckle.AspNetCore` should not break code that relies on the OpenAPI 1.x APIs, or migration instructions should be clearly documented.

## Actual Behavior
Code that previously worked with Microsoft.OpenApi 1.x fails due to breaking changes in 2.x.

## Environment
- Swashbuckle.AspNetCore: 10.1.0
- Microsoft.OpenApi: 2.3.0
- Previous working version: Swashbuckle.AspNetCore 7.2.0 + Microsoft.OpenApi 1.x
- .NET version: 10

## Suggested Fix / Workaround
- Provide a clear migration guide from `Microsoft.OpenApi` 1.x to 2.x
- Consider releasing a Swashbuckle version that maintains compatibility with 1.x APIs

## Additional Context
This breaking change affects projects that depend on the old OpenAPI 1.x types, causing builds to fail immediately after upgrade.
